---
title: "R Notebook"
output: html_notebook
---


```{r}
#Q1: Load the tidyverse package, and use the function read_delim() to read in sample-level metadata that was obtained from the GTEx Portal (GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt). In addition, open the data dictionary GTEx_Analysis_v8_Annotations_SampleAttributesDD.xlsx in Excel, which provides a description of each column in the .txt file.

library(tidyverse)

df <- read_delim("/Users/cmdb/Data/GTEx/GTEx_Analysis_v8_Annotations_SampleAttributesDS.txt")
```

```{r}
#Q2: View the first rows of the tibble by simply entering the variable name in which you stored it. Notice that some of the columns were cut off due to the limits of the display. Use the glimpse() function to examine the data types and first entries of all of the columns.

glimpse(df)
```

```{r}
#Q3: Use the filter() function to subset the dataset to only the RNA-seq data by selecting rows for which the SMGEBTCHT column contains the value "TruSeq.v1". TruSeq is a library preparation kit from Illumina.

df_RNAseq <- filter(df, SMGEBTCHT == "TruSeq.v1")
```

```{r}
#Q4: Plot the number of samples from each tissue (SMTSD) as a barplot. (Hint: if you do not specify a y-axis, ggplot will use stat = count as the default, so the y-axis will represent the number of occurrences of each value of your x variable). See this webpage for a code snippet for rotating axis labels, which will be relevant throughout this exercise. Always be sure to label your axes with informative names!

ggplot(data = df_RNAseq, mapping = aes(x = SMTSD)) +
  geom_bar() +
  xlab("Tissue type") +
  ylab("Frequency") +
  theme_classic() +
  coord_flip()
```

```{r}
#Q5: The RNA integrity number is a measurement of the degree of RNA degradation based on characteristics of an electropherogram trace. It ranges from 1 to 10, with 10 being the least degraded. Plot the distribution of RNA integrity numbers across your samples. What type of plot is best for visualizing a single continuous distribution? Take a look at this “cheat sheet” for hints. What is the shape of the distribution? Is it unimodal?

ggplot(data = df_RNAseq, mapping = aes(x = SMRIN)) +
  geom_histogram(bins = 25) +
  xlab("Tissue type") +
  ylab("Frequency") +
  theme_classic()

#It is unimodal, a histogram will do well
```

```{r}
#Q6: Copy your code from above, but now plot the distribution of RIN, stratified by tissue. Consider what type of plot is best for contrasting continuous distributions across multiple groups. Do you notice any differences across tissues? Are certain tissues outliers? What are your hypotheses to explain these observations?

ggplot(data = df_RNAseq, mapping = aes(x = SMRIN, y = SMTSD)) +
  geom_boxplot() +
  xlab("RIN") +
  ylab("Tissue type") +
  theme_classic()

#The cell lines look like they have the highest RIN. 
```

```{r}
#Q7: Genes accross samples stratified by tissue

ggplot(data = df_RNAseq, mapping = aes(x = SMGNSDTC, y = SMTSD)) +
  geom_boxplot() +
  xlab("No. of genes") +
  ylab("Tissue type") +
  theme_classic()
```
```{r}
#Q8: Plot the relationship between ischemic time and RIN

ggplot(data = df_RNAseq, mapping = aes(x = SMTSISCH, y = SMRIN)) +
  geom_point(size = 0.1, alpha = 0.5) +
  geom_smooth(method = "lm") +
  facet_wrap(~ SMTSD) +
  xlab("Ischemic time (min)") +
  ylab("RIN number") +
  theme_classic() +
  theme(strip.background = element_blank(), 
        strip.text = element_text(face = "bold"))

#As ischemic time increases, RIN number also decreases. This does depend on tissue, as some tissue have steeper trend lines than others.
```

```{r}
#Q9:  Copy your answer from question 6 above, but modify it to color your points by autolysis score

ggplot(data = df_RNAseq, mapping = aes(x = SMTSISCH, y = SMRIN)) +
  geom_point(size = 0.1, alpha = 0.5, aes(color = SMATSSCR)) +
  geom_smooth(method = "lm") +
  facet_wrap(~ SMTSD) +
  xlab("Ischemic time (min)") +
  ylab("RIN number") +
  labs(color = "Autolysis score") +
  theme_classic() +
  theme(strip.background = element_blank(), 
        strip.text = element_text(face = "bold"))

#It looks like the lower the RIN number, the higher the autolysis score. Tissue does affect this, many neural tissues don't autolyse to the same extent other tissues do.
```